Learning_Managerment_SystemMarket_Web/Areas/AdminFunction/Controllers/DashboardController.cs
using AutoMapper;
using Learning_Managerment_SystemMarket_Services.AdminFunction.UserService;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Learning_Managerment_SystemMarket_Web.Areas.AdminFunction.Controllers
{
    [Area("AdminFunction")]
    public class DashboardController : Controller
    {
        private readonly ILogger<UserController> _logger;
        private readonly IMapper _mapper;

        public DashboardController(ILogger<UserController> logger, IMapper mapper)
        {
            _logger = logger;
            _mapper = mapper;
        }
        // GET: DashboardController
        public ActionResult Index()
        {
            return View();
        }
    }
}

Learning_Managerment_SystemMarket_Web/Areas/AdminFunction/Controllers/RoleController.cs
using AutoMapper;
using Learning_Managerment_SystemMarket_Core.Models.Entities;
using Learning_Managerment_SystemMarket_Services.AdminFunction.ClaimService;
using Learning_Managerment_SystemMarket_Services.AdminFunction.RoleService;
using Learning_Managerment_SystemMarket_Services.AdminFunction.UserService;
using Learning_Managerment_SystemMarket_ViewModels.AdminFunctionVm.RoleViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Learning_Managerment_SystemMarket_Web.Areas.AdminFunction.Controllers
{
    [Area("AdminFunction")]
    public class RoleController : Controller
    {
        private readonly ILogger<RoleController> _logger;
        private readonly UserManager<User> _userManager;
        private readonly RoleManager<Role> _roleManager;
        private readonly IUserService _userService;
        private readonly IClaimService _claimService;
        private readonly IRoleService _roleService;
        private readonly IMapper _mapper;

        public RoleController(ILogger<RoleController> logger,
                            IMapper mapper,
                            UserManager<User> userManager,
                            RoleManager<Role> roleManager,
                            IUserService userService,
                            IRoleService roleService,
                            IClaimService claimService)
        {
            _logger = logger;
            _mapper = mapper;
            _userManager = userManager;
            _roleManager = roleManager;
            _userService = userService;
            _roleService = roleService;
            _claimService = claimService;
        }

        public IActionResult ManageRoleClaim(int id)
        {
            ViewBag.IdRole = id;
            return View();
        }

        // GET: RoleController
        public ActionResult Index()
        {
            return View();
        }

        // GET: RoleController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: RoleController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RoleController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(RoleVM newRoleVM)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return RedirectToAction(nameof(ManageRoleClaim));
                }
                var role = new Role() { Name = newRoleVM.Name };
                var claims = new List<Claim>();
                foreach (var item in newRoleVM.ClaimsFake)
                {
                    if (item != null)
                    {
                        claims.Add(new Claim() { ClaimType = item.Trim(), ClaimValue = item.Trim() });
                    }
                }

                var response = await _roleService.Create(role, claims);
                if (!response.Success)
                {
                    ModelState.AddModelError("", response.Message);
                    return RedirectToAction(nameof(ManageRoleClaim));
                }
                return RedirectToAction(nameof(ManageRoleClaim));
            }
            catch
            {
                return RedirectToAction(nameof(ManageRoleClaim));
            }
        }

        // GET: RoleController/Edit/5
        public ActionResult Edit(int id)
        {
            return RedirectToAction(nameof(ManageRoleClaim), new { id = id });
        }

        // POST: RoleController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(RoleVM roleVM)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return RedirectToAction(nameof(ManageRoleClaim));
                }
                var role = await _roleService.Find(x => x.Id == roleVM.Id);
                if (role == null)
                {
                    return RedirectToAction(nameof(ManageRoleClaim), new { id = roleVM.Id });
                }
                role.Name = roleVM.Name;
                var claims = await _claimService.FindAll(x => x.RoleId == roleVM.Id);
                var claimsOlder = claims.Where(x => !roleVM.ClaimsFake.Contains(x.ClaimType.ToString().Trim())).ToList();
                var claimOlderNotRemove = claims.Where(x => roleVM.ClaimsFake.Contains(x.ClaimType.ToString().Trim())).Select(x => x.ClaimValue).ToList();
                foreach (var item in claims)
                {
                    if (item != null)
                    {
                        if (roleVM.ClaimsFake.Contains(item.ClaimValue.Trim()))
                        {
                            roleVM.ClaimsFake.Remove(item.ClaimValue.Trim());
                        }
                    }
                }
                var newClaim = new List<Claim>();
                if (roleVM.ClaimsFake != null)
                {
                    foreach (var item in roleVM.ClaimsFake)
                    {
                        if (item != null && !claimOlderNotRemove.Contains(item))
                        {
                            newClaim.Add(new Claim() { ClaimType = item, ClaimValue = item });
                        }
                    }
                }
                //var claims = role
                var respone = await _roleService.Update(role, newClaim, claimsOlder);
                if (!respone.Success)
                {
                    ModelState.AddModelError("", respone.Message);
                    return RedirectToAction(nameof(ManageRoleClaim), new { id = roleVM.Id });
                }
                return RedirectToAction(nameof(ManageRoleClaim));
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Update not success");
                return RedirectToAction(nameof(ManageRoleClaim));
            }
        }

        // GET: RoleController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return RedirectToAction(nameof(ManageRoleClaim));
                }
                var role = await _roleService.Find(x => x.Id == id);

                if (role == null)
                {
                    ModelState.AddModelError("", "Record not exist");
                    return RedirectToAction(nameof(ManageRoleClaim));
                }
                var respone = await _roleService.Delete(role);
                var responeClaim = await _claimService.Delete(role.Id);
                if (!respone.Success || !responeClaim.Success)
                {
                    return BadRequest();
                }
                return RedirectToAction(nameof(ManageRoleClaim));
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Delete not success");
                return RedirectToAction(nameof(ManageRoleClaim));
            }
        }

        //// POST: RoleController/Delete/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Delete(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

Learning_Managerment_SystemMarket_Web/Areas/AdminFunction/Controllers/UserController.cs
using AutoMapper;
using Learning_Managerment_SystemMarket_Core.Models.Entities;
using Learning_Managerment_SystemMarket_Services.AdminFunction.RoleService;
using Learning_Managerment_SystemMarket_Services.AdminFunction.UserService;
using Learning_Managerment_SystemMarket_ViewModels.AdminFunctionVm.UserViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Learning_Managerment_SystemMarket_Web.Areas.AdminFunction.Controllers
{
    [Area("AdminFunction")]
    public class UserController : Controller
    {
        private readonly ILogger<UserController> _logger;
        private readonly IUserService _userService;
        private readonly IRoleService _roleService;
        private readonly IMapper _mapper;

        public UserController(ILogger<UserController> logger, IUserService userService, IRoleService roleService, IMapper mapper)
        {
            _logger = logger;
            _userService = userService;
            _roleService = roleService;
            _mapper = mapper;
        }

        // GET: UserController
        public ActionResult Index()
        {
            return View();
        }

        public IActionResult ManagerUser(int id)
        {
            ViewBag.IdUser = id;
            return View();
        }

        // POST: UserController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(UserDetailsVm model)
        {
            try
            {
                var allRoles = await _roleService.FindAll();
                var roleItems = new MultiSelectList(allRoles, "Id", "Name");

                model.SelectedRoles = roleItems;

                if (!ModelState.IsValid)
                {
                    return View(model);
                }

                var isUserExist = await _userService.IsExisted(model.UserName);
                if (isUserExist)
                {
                    ModelState.AddModelError("", "User is Existed");
                    return RedirectToAction(nameof(ManagerUser), new { id = model.Id });
                }

                var user = _mapper.Map<User>(model);

                var response = await _userService.Create(user, model.Password);
                if (response.Success == false)
                {
                    ModelState.AddModelError("", response.Message);
                    return RedirectToAction(nameof(ManagerUser));
                }

                var roles = new List<string>();
                foreach (var roleId in model.RolesId)
                {
                    var role = await _roleService.Find(x => x.Id == roleId);
                    roles.Add(role.Name);
                }

                var addRoles = await _userService.AddToRoles(user, roles);
                if (!addRoles.Success)
                {
                    ModelState.AddModelError("", addRoles.Message);
                    return RedirectToAction(nameof(ManagerUser), new { id = model.Id });
                }

                return RedirectToAction(nameof(ManagerUser));
            }
            catch (Exception)
            {
                return View(model);
            }
        }

        // GET: UserController/Edit/5
        public IActionResult Edit(int id)
        {
            return RedirectToAction(nameof(ManagerUser), new { id = id });
        }

        // POST: UserController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(UserEditsVm model)
        {
            try
            {
                var allRoles = await _roleService.FindAll();
                var roleItems = new MultiSelectList(allRoles, "Id", "Name");

                model.SelectedRoles = roleItems;

                if (!ModelState.IsValid)
                {
                    return View(model);
                }

                var user = await _userService.Find(x => x.Id == model.Id);
                if (user == null)
                {
                    return RedirectToAction(nameof(ManagerUser), new { id = model.Id });
                }

                var userRoles = await _userService.GetUserRoles(user);
                var removeRoles = await _userService.RemoveFromRoles(user, userRoles);
                if (!removeRoles.Success)
                {
                    ModelState.AddModelError("", removeRoles.Message);
                    return RedirectToAction(nameof(ManagerUser), new { id = model.Id });
                }

                var roles = new List<string>();
                foreach (var roleId in model.RolesId)
                {
                    var role = await _roleService.Find(x => x.Id == roleId);
                    roles.Add(role.Name);
                }

                var addRoles = await _userService.AddToRoles(user, roles);
                if (!addRoles.Success)
                {
                    ModelState.AddModelError("", addRoles.Message);
                    return RedirectToAction(nameof(ManagerUser), new { id = model.Id });
                }

                user.UserName = model.UserName;
                var respone = await _userService.Update(user);
                if (!respone.Success)
                {
                    ModelState.AddModelError("", respone.Message);
                    return RedirectToAction(nameof(ManagerUser), new { id = model.Id });
                }
                return RedirectToAction(nameof(ManagerUser));
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Update not success");
                return RedirectToAction(nameof(ManagerUser));
            }
        }

        // GET: UserController/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return RedirectToAction(nameof(ManagerUser));
                }
                var user = await _userService.Find(x => x.Id == id);
                if (user == null)
                {
                    ModelState.AddModelError("", "Record not exist");
                    return RedirectToAction(nameof(ManagerUser));
                }
                var response = await _userService.Delete(user);
                if (!response.Success)
                {
                    return BadRequest();
                }
                return RedirectToAction(nameof(ManagerUser));
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Delete not success");
                return RedirectToAction(nameof(ManagerUser));
            }
        }
    }
}

Learning_Managerment_SystemMarket_Web/Controllers/StudentController.cs
using AutoMapper;
using Learning_Managerment_SystemMarket_Services.StudentServices.StudentHomePageService;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Learning_Managerment_SystemMarket_Web.Controllers
{
    public class StudentController : Controller
    {
        private readonly IStudentHomePageService _studentHomePageService;
        private readonly IMapper _mapper;

        public StudentController(IStudentHomePageService studentHomePageService,IMapper mapper)
        {
            this._studentHomePageService = studentHomePageService;
            this._mapper = mapper;
        }
        public IActionResult Index()
        {
            return View();
        }
       
        public IActionResult SavedCourses()
        {
            return View();
        }

        public IActionResult Filter()
        {
            return View(); 
        }

<<<<<<< HEAD
        //public async Task<IActionResult> GetCourseByCategory(int id)
        //{
        //    var course = _studentHomePageService.FindCourse(c => c.CategoryId == id);
        //}
=======
        public async Task<IActionResult> GetCourseByCategory(int id)
        {
            var course = await _studentHomePageService.FindCourse(c => c.CategoryId == id);
            return View();
        }
>>>>>>> 5811c0e0c9c07931fd281ba6e0dcbed146462f7e
    }
}

Learning_Managerment_SystemMarket_Web/Views/Shared/_Categories.cshtml
@inject Learning_Managerment_SystemMarket_Services.StudentServices.StudentHomePageService.IStudentHomePageService service;
@{
    var categories = await service.GetAllCategory();
}
@foreach (var category in categories)
{
    <li style="list-style-type:none" class="sub_menu--item">
        <a asp-area="StudentFunction" asp-action="GetCourseByCategory" asp-controller="Student" asp-route-id="@category.Id" class="sub_menu--link item channel_item">@category.CategoryName</a>
    </li>
}

Learning_Managerment_SystemMarket_Web/Views/Shared/_CountItemCart.cshtml
@using Microsoft.AspNetCore.Identity
@using Learning_Managerment_SystemMarket_Core.Models.Entities;

@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager
@inject Learning_Managerment_SystemMarket_Services.StudentServices.CartService.ICartService cartService;
@{
    var user = await UserManager.GetUserAsync(User);
    var cartItems = await cartService.FindAll(expression: c => c.StudentId == user.IdUser);
}
<span class="noti_count">@cartItems.Count</span>

Learning_Managerment_SystemMarket_Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Learning_Managerment_SystemMarket_Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="/frontend/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/frontend/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/plugins/table/datatable/datatables.css">
    <link rel="stylesheet" type="text/css" href="/plugins/table/datatable/custom_dt_html5.css">
    <link rel="stylesheet" type="text/css" href="/plugins/table/datatable/dt-global_style.css">
    <link href="/js/summernote.min.css" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="/plugins/select2/select2.min.css">

    <link rel="stylesheet" href="/css/style.css">
    <link rel="stylesheet" href="/css/components.css">

    @*CuongNM53*@
    <script src="https://code.jquery.com/jquery-1.8.3.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.css">
    <script type="text/javascript">
        var jq183 = jQuery.noConflict();
    </script>
    <script type="text/javascript">
        jq183(document).ready(function () {
            jq183('.chosen-select').chosen();

            jq183("#btn").click(function () {
                console.log("Button Clicked To Reset");
                jq183('.chosen-select').val("").trigger("chosen:updated");
                jq183('.chosen-select').val("").trigger("liszt:updated");
            });
        });
    </script>
    @*CuongNM53*@


</head>
<body>
    <div class="navbar-bg"></div>
    <nav class="navbar navbar-expand-lg main-navbar">
        <form class="form-inline mr-auto">
            <ul class="navbar-nav mr-3">
                <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
            </ul>
        </form>
        <ul class="navbar-nav navbar-right">
            <li class="dropdown dropdown-list-toggle">
                <a href="#" data-toggle="dropdown" class="nav-link nav-link-lg message-toggle beep"><i class="fa fa-language"></i></a>
                <div class="dropdown-menu dropdown-list dropdown-menu-right">
                    <div class="dropdown-header">
                        Languages

                    </div>
                    <div class="dropdown-list-content dropdown-list-message">
                        <a href="https://coursearly.com/cursus/public/locale/en" class="dropdown-item">
                            <div class="dropdown-item-desc">
                                <b>English</b>
                            </div>
                        </a>
                        <a href="https://coursearly.com/cursus/public/locale/es" class="dropdown-item">
                            <div class="dropdown-item-desc">
                                <b>Spanish</b>
                            </div>
                        </a>
                        <a href="https://coursearly.com/cursus/public/locale/ar" class="dropdown-item">
                            <div class="dropdown-item-desc">
                                <b>arabic</b>
                            </div>
                        </a>
                        <a href="https://coursearly.com/cursus/public/locale/TR" class="dropdown-item">
                            <div class="dropdown-item-desc">
                                <b>Türkçe</b>
                            </div>
                        </a>
                        <a href="https://coursearly.com/cursus/public/locale/Pt" class="dropdown-item">
                            <div class="dropdown-item-desc">
                                <b>Portugues</b>
                            </div>
                        </a>
                        <a href="https://coursearly.com/cursus/public/locale/da" class="dropdown-item">
                            <div class="dropdown-item-desc">
                                <b>da</b>
                            </div>
                        </a>
                    </div>

                </div>
            </li>

            <partial name="~/Views/Shared/PartialViews/_InformationAdmin.cshtml">

        </ul>
    </nav>
    <div class="main-sidebar" tabindex="1" style="overflow: hidden; outline: none;">

        <aside id="sidebar-wrapper">
            <ul class="sidebar-menu">

                <li class="active">
                    <a class="nav-link" asp-area="AdminFunction" asp-controller="Dashboard" asp-action="Index">
                        <i class="fas fa-tachometer-alt"></i>
                        <span>Dashboard</span>
                    </a>
                </li>

                <li class="menu-header">Starter</li>

                <li class="">
                    <a class="nav-link" asp-area="AdminFunction" asp-controller="Role" asp-action="ManageRoleClaim"><i class="far fa-address-book"></i> <span>Role</span></a>
                </li>

                <li class="">
                    <a class="nav-link" asp-area="AdminFunction" asp-controller="User" asp-action="ManagerUser">
                        <i class="far fa-user"></i>
                        <span>Users</span>
                    </a>
                </li>

                <li class="">
                    <a class="nav-link" asp-area="AdminFunction" asp-controller="Language" asp-action="ManagerLanguage">
                        <i class="fas fa-language"></i>
                        <span>Languages</span>
                    </a>
                </li>

                <li class="">
                    <a class="nav-link" asp-area="AdminFunction" asp-controller="Category" asp-action="ManagerCategory">
                        <i class="fas fa-list-ul"></i>
                        <span>Categories</span>
                    </a>
                </li>

                <li class="">
                    <a class="nav-link" asp-area="AdminFunction" asp-controller="SubCategory" asp-action="ManagerSubCategory">
                        <i class="fas fa-boxes"></i>
                        <span>Sub Categories</span>
                    </a>
                </li>
                <li class="menu-header">Students</li>

                <li class="">
                    <a class="nav-link" asp-area="AdminFunction" asp-controller="Student" asp-action="ManagerStudent">
                        <i class="fas fa-user"></i>
                        <span>Student</span>
                    </a>
                </li>
                <li class="menu-header">Instructor</li>

                <li class="">
                    <a class="nav-link" asp-area="AdminFunction" asp-controller="Instructor" asp-action="ManagerInstructor">
                        <i class="fas fa-chalkboard-teacher"></i>
                        <span>Instructor</span>
                    </a>
                </li>
                <li class="nav-item dropdown ">
                    <a href="#" class="nav-link has-dropdown" data-toggle="dropdown">
                        <i class="fas fa-book"></i>
                        <span>Course</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a class="nav-link" asp-area="AdminFunction" asp-controller="Course" asp-action="WaitToApprove">Waiting for approval</a>
                        </li>
                        <li>
                            <a class="nav-link" asp-area="AdminFunction" asp-controller="Course" asp-action="AllCourse">All</a>
                        </li>
                        <li>
                            <a class="nav-link" asp-area="AdminFunction" asp-controller="Course" asp-action="ListReject">Rejected</a>
                        </li>
                    </ul>
                </li>
            </ul>

        </aside>
    </div>
    <div class="main-content" style="min-height: 861px;">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="main-footer">
        <div class="footer-left">
            &copy; 2021 - Learning_Managerment_SystemMarket_Web <div class="bullet"></div> Design By <a href="">Team</a>
        </div>
        <div class="footer-right">
            1.0.2
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="/frontend/js/jquery.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="/frontend/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="/js/nicescroll.min.js"></script>
    <script src="/js/moment.min.js"></script>

    <script src="/plugins/table/datatable/datatables.js"></script>
    <script src="/plugins/table/datatable/button-ext/dataTables.buttons.min.js"></script>
    <script src="/plugins/table/datatable/button-ext/jszip.min.js"></script>
    <script src="/plugins/table/datatable/button-ext/buttons.html5.min.js"></script>
    <script src="/plugins/table/datatable/button-ext/buttons.print.min.js"></script>
    <script src="/js/stisla.js"></script>
    <script src="/plugins/select2/select2.min.js"></script>
    <script src="/js/scripts.js"></script>
    <script src="/js/custom.js"></script>
    <script src="/js/chart.js"></script>

    <script src="/js/summernote.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <script>
        $(document).ready(function () {
            $('#admin-dropdown').click(function (e) {
                if ($('#admin-function').hasClass("hidden")) {
                    $('#admin-function').removeClass("hidden");
                    $('#admin-function').addClass("show");
                }
                else {
                    $('#admin-function').removeClass("show");
                    $('#admin-function').addClass("hidden");
                }
            })
        });
    </script>
</body>
</html>