Learning_Managerment_SystemMarket_Web/Areas/AdminFunction/Controllers/InstructorController.cs
using AutoMapper;
using Learning_Managerment_SystemMarket_Core.Modules.Enums;
using Learning_Managerment_SystemMarket_Services.AdminFunction.InstructorService;
using Learning_Managerment_SystemMarket_Services.InstructorServices.CourseService;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;

namespace Learning_Managerment_SystemMarket_Web.Areas.AdminFunction.Controllers
{
    [Area("AdminFunction")]
    public class InstructorController : Controller
    {
        private readonly ILogger<InstructorController> _logger;
        private readonly IInstructorService _instructorService;
        private readonly ICourseServices _courseService;
        private readonly IMapper _mapper;

        public InstructorController(ILogger<InstructorController> logger, IInstructorService instructorService, IMapper mapper, ICourseServices courseService)
        {
            _logger = logger;
            _instructorService = instructorService;
            _mapper = mapper;
            _courseService = courseService;
        }

        // GET: InstructorController
        public ActionResult Index()
        {
            return View();
        }

        public IActionResult ManagerInstructor()
        {
            return View();
        }

        // GET: StudentController/Details/5
        public ActionResult ViewInfo(int id, int idIns)
        {
            ViewBag.IdCourse = id;
            ViewBag.IdInstructor = idIns;
            return View();
        }

        // GET: StudentController/Details/5
        public ActionResult InstructorInfo(int id)
        {
            ViewBag.IdInstructor = id;
            return View();
        }

        // GET: InstructorController/Details/5
        public async Task<ActionResult> ChangeBlockInstructor(int id)
        {
            var instructor = await _instructorService.Find(x => x.Id == id);
            if (instructor == null)
            {
                return RedirectToAction(nameof(ManagerInstructor));
            }

            if (instructor.Status == StatusIns.Active)
            {
                instructor.Status = StatusIns.Deactive;
            }
            else
            {
                instructor.Status = StatusIns.Active;
            }

            var respone = await _instructorService.Update(instructor);
            if (!respone.Success)
            {
                ModelState.AddModelError("", respone.Message);
                return RedirectToAction(nameof(ManagerInstructor));
            }
            return RedirectToAction(nameof(ManagerInstructor));
        }
        public async Task<ActionResult> ChangeBlockCourse(int id, int idIns)
        {
            var course = await _courseService.Find(x => x.Id == id);
            if (course == null)
            {
                return RedirectToAction(nameof(InstructorInfo), new { id = idIns });
            }
            if (course.Status == StatusCourse.Active)
            {
                course.Status = StatusCourse.Deactive;
            }
            else
            {
                course.Status = StatusCourse.Active;
            }
            var respone = await _courseService.Update(course);
            if (!respone.Success)
            {
                ModelState.AddModelError("", respone.Message);
                return RedirectToAction(nameof(InstructorInfo), new { id = idIns });
            }
            return RedirectToAction(nameof(InstructorInfo), new { id = idIns });
        }
        // GET: InstructorController/Details/5
        public async Task<ActionResult> ChangeBestSeller(int id, int idIns)
        {
            var course = await _courseService.Find(x => x.Id == id);
            if (course == null)
            {
                return RedirectToAction(nameof(InstructorInfo), new { id = idIns });
            }

            if (course.IsBestseller)
            {
                course.IsBestseller = false;
            }
            else
            {
                course.IsBestseller = true;
            }

            var respone = await _courseService.Update(course);
            if (!respone.Success)
            {
                ModelState.AddModelError("", respone.Message);
                return RedirectToAction(nameof(InstructorInfo), new { id = idIns });
            }
            return RedirectToAction(nameof(InstructorInfo), new { id = idIns });
        }

        // GET: InstructorController/Details/5
        public async Task<ActionResult> ChangeFeatured(int id, int idIns)
        {
            var course = await _courseService.Find(x => x.Id == id);
            if (course == null)
            {
                return RedirectToAction(nameof(InstructorInfo), new { id = idIns });
            }

            if (course.IsFeatured)
            {
                course.IsFeatured = false;
            }
            else
            {
                course.IsFeatured = true;
            }

            var respone = await _courseService.Update(course);
            if (!respone.Success)
            {
                ModelState.AddModelError("", respone.Message);
                return RedirectToAction(nameof(InstructorInfo), new { id = idIns });
            }
            return RedirectToAction(nameof(InstructorInfo), new { id = idIns });
        }
    }
}

Learning_Managerment_SystemMarket_Web/Areas/StudentFunction/Controllers/CartController.cs
using AutoMapper;
using Learning_Managerment_SystemMarket_Core.Contracts;
using Learning_Managerment_SystemMarket_Core.Models.Entities;
using Learning_Managerment_SystemMarket_Services.StudentServices.CartService;
using Learning_Managerment_SystemMarket_Services.StudentServices.OrderService;
using Learning_Managerment_SystemMarket_Services.StudentServices.SavedCourseService;
using Learning_Managerment_SystemMarket_Services.StudentServices.StudentExploreService;
using Learning_Managerment_SystemMarket_Services.StudentServices.StudentHomePageService;
using Learning_Managerment_SystemMarket_Services.StudentServices.SubcriptionService;
using Learning_Managerment_SystemMarket_ViewModels.StudentViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Learning_Managerment_SystemMarket_Web.Areas.StudentFunction.Controllers
{
    [Area("StudentFunction")]
    public class CartController : Controller
    {
        private readonly IStudentHomePageService _studentHomePageService;
        private readonly IMapper _mapper;
        private readonly IStudentExploreService _studentExploreService;
        private readonly IUnitOfWork _unitOfWork;
        private readonly ISavedCourseService _savedCourseService;
        private readonly ISubcriptionService _subcriptionService;
        private readonly ICartService _cartService;
        private readonly IOrderService _orderService;
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;

        public CartController(
            IStudentHomePageService studentHomePageService,
            ISavedCourseService savedCourseService,
            IUnitOfWork unitOfWork,
            IMapper mapper,
            IStudentExploreService studentExploreService,
            ISubcriptionService subcriptionService,
            UserManager<User> userManager,
            SignInManager<User> signInManager,
            ICartService cartService,
            IOrderService orderService)

        {
            _studentHomePageService = studentHomePageService;
            _mapper = mapper;
            _studentExploreService = studentExploreService;
            _unitOfWork = unitOfWork;
            _savedCourseService = savedCourseService;
            _subcriptionService = subcriptionService;
            _userManager = userManager;
            _signInManager = signInManager;
            _cartService = cartService;
            _orderService = orderService;
        }

        /// <summary>
        /// Get all cart by student id VuTV10
        /// </summary>
        /// <param name="id">Student id</param>
        /// <returns>List cart of student</returns>
        public async Task<IActionResult> GetCartByStudentId(int? id)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return View(new CartVM());
            }
            if (id == null)
                id = user.IdUser;

            var cartItems = await _cartService.FindAll(
                expression: c => c.StudentId == id,
                includes: new List<string> { "Course" });

            var cart = new CartVM
            {
                Carts = cartItems,
                Total = cartItems.Sum(c => c.Course.Price)
            };
            return View(cart);
        }

        /// <summary>
        /// Add course to cart VuTV10
        /// </summary>
        /// <param name="courseId">Course Id</param>
        /// <param name="studentId">Student Id</param>
        /// <returns>Success</returns>
        public async Task<IActionResult> AddCourseToCart(int courseId, int studentId)
        {
            try
            {
                var existingCart = await _cartService.Find(expression: c => c.CourseId == courseId && c.StudentId == studentId);
                if (existingCart != null)
                {
                    return RedirectToAction(nameof(GetCartByStudentId));
                }
                var cart = new Cart
                {
                    CourseId = courseId,
                    StudentId = studentId,
                    CreatedDate = DateTime.Now
                };
                var respon = await _cartService.Create(cart);
                if (!respon.Success)
                {
                    return BadRequest();
                }
                return RedirectToAction(nameof(GetCartByStudentId));
            }
            catch (Exception)
            {
                return BadRequest();
            }
        }

        /// <summary>
        /// Delete course from cart VuTV10
        /// </summary>
        /// <param name="courseId">Course id</param>
        /// <param name="studentId">Student id</param>
        /// <returns>Success</returns>
        public async Task<IActionResult> DeleteCourseFromCart(int courseId, int studentId)
        {
            try
            {
                var cart = await _cartService.Find(expression: c => c.CourseId == courseId && c.StudentId == studentId);
                var respon = await _cartService.Delete(cart);
                if (!respon.Success)
                {
                    return BadRequest();
                }
                return RedirectToAction(nameof(GetCartByStudentId));
            }
            catch (Exception)
            {
                return BadRequest();
            }
        }

        /// <summary>
        /// Checkout cart VuTV10
        /// </summary>
        /// <param name="studentId">Student Id</param>
        /// <returns>Success or false</returns>
        public async Task<IActionResult> Payment(int studentId)
        {
            try
            {
                var respon = await _cartService.Payment(studentId);
                if (!respon.Success)
                {
                    return BadRequest();
                }
                return RedirectToAction(nameof(GetCartByStudentId));
            }
            catch (Exception)
            {
                return BadRequest();
            }
        }
        /// <summary>
        /// Get enrolled courses by Student Id VuTV10
        /// </summary>
        /// <returns>List enrolled course</returns>
        public async Task<IActionResult> EnrolledCourse()
        {
            var user = await _userManager.GetUserAsync(User);
            var orders = await _orderService.FindAll(expression: o => o.StudentId == user.IdUser);
            return View(orders);
        }
    }
}

Learning_Managerment_SystemMarket_Web/Controllers/StudentController.cs
using AutoMapper;
using Learning_Managerment_SystemMarket_Services.StudentServices.StudentHomePageService;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Learning_Managerment_SystemMarket_Web.Controllers
{
    public class StudentController : Controller
    {
        private readonly IStudentHomePageService _studentHomePageService;
        private readonly IMapper _mapper;

        public StudentController(IStudentHomePageService studentHomePageService,IMapper mapper)
        {
            this._studentHomePageService = studentHomePageService;
            this._mapper = mapper;
        }
        public IActionResult Index()
        {
            return View();
        }
       
        public IActionResult SavedCourses()
        {
            return View();
        }

        public IActionResult Filter()
        {
            return View(); 
        }

<<<<<<< HEAD
        //public async Task<IActionResult> GetCourseByCategory(int id)
        //{
        //    var course = _studentHomePageService.FindCourse(c => c.CategoryId == id);
        //}
=======
        public async Task<IActionResult> GetCourseByCategory(int id)
        {
            var course = await _studentHomePageService.FindCourse(c => c.CategoryId == id);
            return View();
        }
>>>>>>> 5811c0e0c9c07931fd281ba6e0dcbed146462f7e
    }
}

Learning_Managerment_SystemMarket_Web/Areas/StudentFunction/Views/Cart/EnrolledCourse.cshtml
@model IEnumerable<Learning_Managerment_SystemMarket_Core.Models.Entities.Order>
@inject Learning_Managerment_SystemMarket_Services.StudentServices.CourseRateService.ICourseRateService courseRateService;
@{
    ViewData["Title"] = "EnrolledCourse";
    Layout = "/Views/Shared/_StudentLayout.cshtml";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-3 col-md-4 ">
            <div class="section3125 hstry142">
                <div class="grp_titles pt-0">
                    <div class="ht_title">Buy Courses</div>

                </div>
                <div class="tb_145">
                    <div class="wtch125">
                        <span class="vdt14">@Model.Count() Buy Courses</span>
                    </div>

                </div>
            </div>
        </div>
        <div class="col-md-9">
            <div class="_14d25 mb-20">
                <div class="row">
                    <div class="col-md-12">
                        <h4 class="mhs_title">Buy Courses</h4>
                        @foreach (var item in Model)
                        {
                            <div class="fcrse_1 mb-30">
                                <a asp-area="StudentFunction" asp-controller="Student" asp-action="CourseDetails" asp-route-id="@item.CourseId" class="hf_img">
                                    @if (item.Course.CoverImage != null)
                                    {
                                        var base64 = Convert.ToBase64String(item.Course.CoverImage);
                                        var imgsrc = string.Format("data:image/jpg;base64,{0}", base64);
                                        <img src="@imgsrc" alt="@item.Course.Title">
                                    }
                                    <div class="course-overlay">
                                        <div class="crse_reviews">
                                            @{ 
                                                var courseRates = await courseRateService.AvgCourseRate(item.CourseId);
                                            }
                                            <i class="uil uil-star"></i>@courseRates
                                        </div>

                                        <span class="play_btn1"><i class="uil uil-play"></i></span>
                                        <div class="crse_timer">
                                            0 hours
                                        </div>
                                    </div>
                                </a>
                                <div class="hs_content">
                                    <div class="eps_dots eps_dots10 more_dropdown">
                                        <a href="#"><i class="uil uil-ellipsis-v"></i></a>
                                        <div class="dropdown-content">
                                            <a href="https://coursearly.com/cursus/public/order-invoice/25" target="_blank"><span><i class="uil uil-print"></i>Invoice</span></a>
                                        </div>
                                    </div>
                                    <div class="vdtodt">
                                        <span class="vdt14">
                                            @item.Course.Views
                                            views
                                        </span>
                                        @{ 
                                            var days = (DateTime.Now - item.CreatedDate).Days;
                                        }
                                        <span class="vdt14">@days days ago</span>
                                    </div>
                                    <a asp-area="StudentFunction" asp-controller="Student"
                                       asp-action="CourseDetails" asp-route-id="@item.CourseId" 
                                       class="crse14s title900">
                                    @item.Course.Title
                                    </a>
                                    <a asp-area="StudentFunction" asp-action="GetCourseByCategory" 
                                       asp-controller="Student" asp-route-id="@item.Course.CategoryId" class="crse-cate">
                                        @item.Course.Category.CategoryName
                                    </a>
                                    <div class="auth1lnkprce">
                                        <p class="cr1fot">
                                            By <a asp-area="StudentFunction" asp-controller="Instructor" asp-action="InstructorDetails"
                                           asp-route-id="@item.Course.InstructorId">@item.Course.Instructor.InstructorName</a>
                                        </p>
                                        <div class="prce142">
                                            $@item.Course.Price
                                        </div>
                                    </div>
                                    <div class="auth1lnkprce">
                                        <p class="cr1fot">
                                            buy at @item.CreatedDate
                                        </p>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Learning_Managerment_SystemMarket_Web/Areas/StudentFunction/Views/Cart/GetCartByStudentId.cshtml
@model Learning_Managerment_SystemMarket_ViewModels.StudentViewModels.CartVM
@using Learning_Managerment_SystemMarket_Core.Models.Entities;
@using Microsoft.AspNetCore.Identity

@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

@{
    ViewData["Title"] = "Shopping Cart";
    Layout = "/Views/Shared/_StudentLayout.cshtml";
    var user = await UserManager.GetUserAsync(User);
}

@if (Model.Carts == null)
{
    <div class="col-md-12">
        <div class="_14d25">
            <div class="row mt-30">
                <div class="col-md-12 text-center">
                    <div class="no-data-div">
                        <img src="https://coursearly.com/cursus/public/nodata.svg" alt="No Data" srcset="">
                    </div>
                </div>

                <div class="col-md-12 text-center">
                    <div class="main-loader mt-50">
                    </div>
                </div>
            </div>
        </div>
    </div>
}
else
{
    <h2 class="mx-auto mt-4 text-center text-success">Shopping Cart</h2>
    <table id="tblData" class="table">
        <thead>
            <tr>
                <th>
                    Title
                </th>
                <th>
                    Image
                </th>
                <th>
                    Price
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Carts)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Course.Title)
                    </td>
                    <td>
                        @if (item.Course.CoverImage != null)
                        {
                            var base64 = Convert.ToBase64String(item.Course.CoverImage);
                            var imgsrc = string.Format("data:image/jpg;base64,{0}", base64);
                            <img style="width:65px; height: 50px;" src="@imgsrc" alt="">
                        }
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Course.Price)
                    </td>
                    <td>
                        <a asp-action="DeleteCourseFromCart" asp-route-courseId="@item.CourseId"
                           asp-route-studentId="@item.StudentId" class="btn btn-danger"
                           onclick="return confirm('Are you sure want to delete this course from cart?')">
                            <i class="uil uil-trash-alt"></i> Delete
                        </a>
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td>
                    Total: @Model.Total $
                </td>
            </tr>
        </tfoot>
    </table>
    @if (Model.Carts.Count() > 0)
    {
        <a asp-area="StudentFunction" asp-controller="Cart" asp-action="Payment"
           asp-route-studentId="@user.IdUser" class="btn btn-warning"
           onclick="return alert('Success')">
            Buy
        </a>
    }
}
@section Scripts{
    <script>
        $(document).ready(function () {
            $('#tblData').DataTable();
        });
    </script>
}